project_id = "oczsddmantovkqfwczqk"

[functions.paystack-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.process-group-buy-goals]
verify_jwt = false

[functions.process-payment-deadlines]
verify_jwt = false

[functions.verify-waitlist-social]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = false

[functions.track-email]
verify_jwt = false

[functions.scan-product-prices]
verify_jwt = false

[functions.bulk-match-competitors]
verify_jwt = false

[functions.auto-match-price]
verify_jwt = false

[functions.bulk-scan-prices]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.enrich-product-details]
verify_jwt = false

[functions.delete-all-products]
verify_jwt = false

[functions.reset-password-with-token]
verify_jwt = false

[functions.calculate-promo-discount]
verify_jwt = false

[functions.debug-order]
verify_jwt = false

[functions.admin-credit-wallet]
verify_jwt = true

[functions.search-market-prices-ng]
verify_jwt = true

[functions.generate-reseller-sales-brief]
verify_jwt = false

[functions.process-influencer-compliance]
verify_jwt = false

[functions.paystack-create-virtual-account]
enabled = true
verify_jwt = true
import_map = "./functions/paystack-create-virtual-account/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/paystack-create-virtual-account/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/paystack-create-virtual-account/*.html" ]
